name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mgenteluci/cloudformation-deploy-action@v1.3.0
      env:
        TEMPLATE: './template.yaml'
        CAPABILITIES: CAPABILITY_NAMED_IAM
        AWS_STACK_NAME: 'auth-user-production'
        AWS_REGION: 'ap-southeast-2'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
        PARAMETER_OVERRIDES: CognitoDomainCertificateArn=arn:aws:acm:ap-southeast-2:740876047172:certificate/61e7e826-acf9-48f9-b918-74ba06aff5c9 EnvironmentName=production FromEmailAddress=no-reply@thoud.co HostedZoneUrl=thoud.co ReplyEmailAddress=no-reply@thoud.co ServiceName=auth SESConfigurationSet=thoud-production SESEmailAddressArn=arn:aws:ses:us-east-1:740876047172:identity/no-reply@thoud.co 
